export const COFFEE_BRANDS = 'COFFEE_BRANDS';
export const COFFEE_BRANDS_FACTORY_LAMBDA = 'COFFEE_BRANDS_FACTORY_LAMBDA';
export const COFFEE_BRANDS_FACTORY_INJECT = 'COFFEE_BRANDS_FACTORY_INJECT';
export const COFFEE_BRANDS_ASYNC = 'COFFEE_BRANDS_ASYNC';
