version: "3"

services:
  db:
    image:  postgres
    restart: always 
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123

  test-db:
  image: postgres
  restart: always
  ports:
    - "5433:5432" # 👈 Note the 5433 port (since we are using 5432 for our regular db)
  environment:
    POSTGRES_PASSWORD: pass123
